### ISSUE TITLE
pr-housekeeping autoapprove doesn't always work

### ISSUE THREAD

**Issue by matthew-puku** [ausaccessfed/workflows#118]
See https://github.com/ausaccessfed/federationmanager/pull/3492 for a recent example.

Could be a race condition? Not sure if the PR is labelled immediately on create or if that happens afterward, from GitHub's perspective.

**Comment by phyzical** [comment]
confirmed it looks to be a race condition with the linked issue, 

We could implement https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#wait-timer, but this is only available for enterprise.

so instead i will add an initial step that sleeps for 1 minute to avoid locking us deeper into enterprise

**Comment by matthew-puku** [comment]
still happens: https://github.com/ausaccessfed/federationmanager/pull/3908

I think perhaps `context` is set when the overall workflow starts, so sleeping 30s in a step doesn't work.

Could perhaps remove the sleep and instead make an API call for the labels if they're missing, retrying with an exponential backoff up to X minutes (two?)
