### ISSUE TITLE
Don't start a mysql service

### ISSUE THREAD

**Issue by ritchiey** [ausaccessfed/workflows#26]
Currently [starts a mysql service in deploy-sync.yml](https://github.com/ausaccessfed/workflows/blob/9894d5aaea227ec5f46a0560f1fcfd4bfd75d86c/.github/workflows/deploy-sync.yml#L101) even though its only needed by a few projects.

This adds a few seconds to each build.

[FM has been modified](https://github.com/ausaccessfed/federationmanager/pull/2783) to run its tests in compose so it brings its own mysql.

I suggest that we do the same for any other projects that need mysql and then we can remove this service from CI.

## Projects using the deploy-sync workflow:
| Project | Requires MySQL Service |
|--------|--------|
| ShibSP | No |
| Discovery Service | No |
| Verifid | |
| Metadata Distribution | No | 
| Validator Service | |
| RapidIDP Manager | |
| Reporting Service | |
| Rapid Connector | |
| [federationmanager](https://github.com/ausaccessfed/federationmanager) | No |
| [oidc_relying_party_example](https://github.com/ausaccessfed/oidc_relying_party_example) | |
| [idp](https://github.com/ausaccessfed/idp) | |

**Comment by matthew-puku** [comment]
Relates to https://github.com/ausaccessfed/discovery-service/issues/354

**Comment by phyzical** [comment]
think a few seconds is worth additional per project configurations imo

**Comment by phyzical** [comment]
actually we might jsut be able to do this https://github.com/actions/runner/issues/822
