### ISSUE TITLE
Skip checks on /deploy to development

### ISSUE THREAD

**Issue by matthew-puku** [ausaccessfed/workflows#28]
# Problem

/deploy is (unfortunately) the only way to test changes involving Shib-SP. Some other types of work are also easiest to test with /deploy. This means we use it a lot.

Currently, the feedback loop for changes involving /deploy is slow. In the best case, it's 15 minutes if you have a fully cached build, watch GitHub and ArgoCD like a hawk, and manually sync the new app version and promote the rollout. More realistically, it takes half an hour. If someone else is using dev, it could take days 😄 

The length of this feedback loop is probably the biggest constraint on two important pieces of work:

- debugging intermittent authn failures in OIDC/Rapid Connect
- adding synthetic entity descriptors to OIDC/Rapid Connect.

# Proposal

On /deploy, just attempt to build a production image, ship it to dev, and update the commit status. Don't run rubocop, or build a test image, or whatever.

I can't think of a single case where I've used /deploy and cared about whether the test suite passes. And anyway, if I did care, I could just check the state of the default workflow. So there's no real loss of functionality here.

# Implementation idea

[The deploy-sync workflow](https://github.com/ausaccessfed/workflows/blob/main/.github/workflows/deploy-sync.yml) has a lot of conditionals, most of which handle the `/deploy` case. It might be simpler to understand and maintain if `/deploy` were split into its own flow. After this ticket, it would not have much in common with the normal flow.

**Comment by phyzical** [comment]
i dont think /deploy does though?

`if: inputs.event_name != 'issue_comment' && inputs.extra_task_1 != '' && always()` 

Yeah currently the tasks dont run.

In shib-sps case its literately how long it takes to build ><

**Comment by matthew-puku** [comment]
Bummer, I thought this was low-hanging fruit to improve the situation. Didn't realise it had already been picked!

**Comment by phyzical** [comment]
Im sure we could improve it though.

But would require doing a refresher on the overall docker build.

Probably best if new eyes attacked it tbh.

**Comment by matthew-puku** [comment]
I agree. Bo is pretty good at this stuff, maybe he will have a go once he reaches a stopping point in the feature work.
