### ISSUE TITLE
Don't run all actions for `/deploy`

### ISSUE THREAD

**Issue by waldofouche** [ausaccessfed/workflows#321]
Ideally should skip all checks for `/deploy` and just build the image then ship it, saves waiting around for the checks to pass:

https://github.com/ausaccessfed/federationmanager/actions/runs/10626160619

**Comment by waldofouche** [comment]
Will save some $$ on build minutes as well

**Comment by phyzical** [comment]
it already does.

**Comment by waldofouche** [comment]
the current action ran all the checks, pls check the link

**Comment by phyzical** [comment]
<img width="915" alt="image" src="https://github.com/user-attachments/assets/e034099f-2d15-4a71-83b9-583043e3dd19">

please check properly lol

**Comment by phyzical** [comment]
we still run the cve checks by design

**Comment by waldofouche** [comment]
is it not possible to skip the setup and inits?

**Comment by phyzical** [comment]
i think the resoning was if we did do that then, we needed to have logic of like "continue on error" then we needed to be suuuuper careful about which steps could still work on error.

Basically i just decided complexity wise this is the smarter safer choice.

WE are not running out of minutes/ build costs anyway are we?

**Comment by waldofouche** [comment]
We are getting close, got pinged a few times before the bill reset. 

![Screenshot 2024-08-30 at 1 26 02 PM](https://github.com/user-attachments/assets/207e35ee-c5dd-4c3b-8159-102c634bd7ad)

I'm all for running the checks, it just seems redundant on deploys do dev that is all

**Comment by phyzical** [comment]
that was last month when we were building for amd still

**Comment by phyzical** [comment]
I think the other reason is if you start skipping it then causes the follow steps to not run that are dependant on the skipped step, its simply treats the following steps as. "skipped". so then you need to add "always()" to every single step then also check if ALL the previous steps had failed or not

**Comment by waldofouche** [comment]
That makes sense, i just thought it be an easy win to shave like 5ish mins off the /deploy time, all good

**Comment by phyzical** [comment]
if you can come up with a more elegant way, im not opposed but im not sure its possible

**Comment by phyzical** [comment]
if we do run out of build monites next monthw e can reconsider making it more coimplicated to save some more $$$ but i think we will be okay for now

**Comment by waldofouche** [comment]
https://github.com/ausaccessfed/workflows/pull/322 was able to shave off ~5mins 20 on the /deploys

**Comment by waldofouche** [comment]
Looks like this has regressed, all checks are being run on `/deploy` cmds

**Comment by phyzical** [comment]
no its still working as intended,

It skips the test commands
