### ISSUE TITLE
Create PR template for `tidying-licenses` request

### ISSUE THREAD

**Issue by waldofouche** [ausaccessfed/workflows#390]
turn https://github.com/ausaccessfed/workflows/pull/389 and https://github.com/ausaccessfed/workflows/pull/289 into a template. 

Maybe it lives in slab, maybe it lives in here. Will help streamline the process. But copy pasta of prs work too

**Comment by phyzical** [comment]
I still dont think the tidying flow is a good one tbh.

(also the effort to make this into a template was probably as much as it was to make this issue :P)

for example for a bug report

`.github/ISSUE_TEMPLATE/bug_report.md`

```
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Unraid version**

**Any logs**
i.e

* /var/log/phplog - for php error logs
* right click and inspect check the console for js errors

**Additional context**
Add any other context about the problem here.

```

**Comment by waldofouche** [comment]
Yeah true lol, will update the slab
